# Generated by Django 6.0.6 on 2026-06-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre_equipo', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno / Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'De Baja / Inoperativo')], default='BUENO', max_length=20)),
                ('ubicacion', models.CharField(help_text='Ej: Área de Capacitación, Recepción', max_length=150)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='datos_contacto',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='nombres_completos',
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='apellidos',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='nombres',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FACILITADOR', 'Facilitador'), ('TECNICO', 'Técnico de Soporte'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20),
        ),
    ]
