# Generated by Django 6.0.6 on 2026-06-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventario_remove_ciudadano_datos_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('CAPACITACION', 'Capacitación / Curso'), ('TRAMITE', 'Trámite Ciudadano'), ('NAVEGACION', 'Navegación Libre / Internet'), ('SOPORTE', 'Asistencia Técnica / Consulta')], max_length=30)),
                ('observaciones', models.TextField(blank=True, help_text='Detalle del trámite o tema de consulta', null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(help_text='Ciudadano que asiste al Punto Digital', on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.ciudadano')),
                ('equipo_asignado', models.ForeignKey(blank=True, help_text='Equipo tecnológico prestado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='core.inventario')),
                ('facilitador', models.ForeignKey(help_text='Personal que registra la visita', on_delete=django.db.models.deletion.PROTECT, related_name='visitas_atendidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
